---
- hosts: all
  become: true
  vars:
    ansible_user: alexei

  tasks:
    - name: Test SSH connection and ping
      ansible.builtin.command:
        cmd: ping -c 4 8.8.8.8
      register: ping_result

    - name: Show ping result
      ansible.builtin.debug:
        msg: "{{ ping_result.stdout_lines }}"

    - name: Test lookup from Semaphore key store
      debug:
        msg:
          - "ansible_user: {{ lookup('semaphore', 'ROOT-PASSWORD.username') }}"
          - "user_ssh_key: {{ lookup('semaphore', 'USER-PUBKEY.key') }}"
          - "user_name: {{ lookup('semaphore', 'USER-PUBKEY.username') }}"

...
