---
- hosts: all
  become: true
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"

  tasks:
    - name: Test SSH connection and ping
      ansible.builtin.command:
        cmd: ping -c 4 8.8.8.8
      register: ping_result

    - name: Show ping result
      ansible.builtin.debug:
        msg: "{{ ping_result.stdout_lines }}"

...
