---
- hosts: all
  become: true
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"

  tasks:
    - name: Debug-Variablen
      debug:
        msg: "user_ssh_key: {{ user_ssh_key }}, user_name: {{ user_name }}"
    - name: Detect operating system
      ansible.builtin.shell: |
        if grep -qi ubuntu /etc/os-release; then
          echo "Ubuntu detected."
        elif grep -qi debian /etc/os-release; then
          echo "Debian detected."
        else
          echo "Unsupported operating system. Exiting."
          exit 1
        fi
      register: os_output
      changed_when: false

    - name: Upgrade system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

...
