---
- hosts: all
  become: true
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"

  tasks:
    - name: Detect operating system
      ansible.builtin.shell: |
        if grep -qi ubuntu /etc/os-release; then
          echo "Ubuntu detected."
        elif grep -qi debian /etc/os-release; then
          echo "Debian detected."
        else
          echo "Unsupported operating system. Exiting."
          exit 1
        fi
      register: os_output
      changed_when: false

    - name: Check for available updates
      ansible.builtin.shell: |
        LC_ALL=C apt list --upgradeable 2>/dev/null | grep -v "^Listing" | wc -l
      register: update_count
      changed_when: false

    - name: Upgrade system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      register: upgrade_result

    - name: Set fact for updates installed
      set_fact:
        updates_installed: "{{ updates_installed | default(0) + (update_count.stdout | int) }}"
      when: upgrade_result.changed

    - name: Display number of updates installed
      ansible.builtin.debug:
        msg: "A total of {{ update_count.stdout }} updates were installed on {{ inventory_hostname }}."
      when: upgrade_result.changed
...
