---
- hosts: all
  become: yes
  vars:
    ansible_user: "{{ lookup('semaphore', 'ROOT-PASSWORD.username') }}"
    ansible_password: "{{ lookup('semaphore', 'ROOT-PASSWORD.password') }}"

  tasks:
    - name: Upgrade system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

...
