---
- hosts: all
  become: true
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"

  tasks:
    - name: Detect operating system
      ansible.builtin.shell: |
        if grep -qi ubuntu /etc/os-release; then
          echo "Ubuntu detected."
        elif grep -qi debian /etc/os-release; then
          echo "Debian detected."
        else
          echo "Unsupported operating system. Exiting."
          exit 1
        fi
      register: os_output
      changed_when: false

    - name: Update apt cache with retries
      ansible.builtin.shell: |
        apt update || (grep 'NO_PUBKEY' /var/log/apt/term.log | awk '{print $21}' | xargs -r -I '{}' apt-key adv --keyserver keyserver.ubuntu.com --recv-keys '{}')
      register: apt_update_result
      retries: 3
      delay: 10
      until: apt_update_result.rc == 0
      changed_when: false

    - name: Upgrade system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      register: upgrade_result
...
